<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Заголовок</name>
   <tag></tag>
   <elementGuidId>f14f2154-ee04-4c1f-87bd-111e6eb0f49c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='edit-type']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'edit-type' and @name = 'type' and (text() = '- Любой -Push повідомленняІнформаційний блок для продуктової сторінкиІнформаційний блок з зображенням для продуктової сторінкиАкордеонАкордеон з файламиАрхівБазовый блокБанерБлок Слайдер з ВідеоБлок для ВідеоБлок для контактівИнфо Блок PopUpКалькуляторКонфігЛендинг БлокМапаПартнеры банкаПлатіжні карткиПортфель кредитной задолженностиПідпискаРасчет даты вылетаТабиТаблийця APIТаблицяФорми' or . = '- Любой -Push повідомленняІнформаційний блок для продуктової сторінкиІнформаційний блок з зображенням для продуктової сторінкиАкордеонАкордеон з файламиАрхівБазовый блокБанерБлок Слайдер з ВідеоБлок для ВідеоБлок для контактівИнфо Блок PopUpКалькуляторКонфігЛендинг БлокМапаПартнеры банкаПлатіжні карткиПортфель кредитной задолженностиПідпискаРасчет даты вылетаТабиТаблийця APIТаблицяФорми')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-type</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-type</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>type</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Любой -Push повідомленняІнформаційний блок для продуктової сторінкиІнформаційний блок з зображенням для продуктової сторінкиАкордеонАкордеон з файламиАрхівБазовый блокБанерБлок Слайдер з ВідеоБлок для ВідеоБлок для контактівИнфо Блок PopUpКалькуляторКонфігЛендинг БлокМапаПартнеры банкаПлатіжні карткиПортфель кредитной задолженностиПідпискаРасчет даты вылетаТабиТаблийця APIТаблицяФорми</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-type&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='edit-type']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='views-exposed-form-block-content-page-1']/div/div[2]/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Тип блока'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Описание блока'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Мова перекладу'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Описание блока'])[2]/preceding::select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
   </webElementXpaths>
</WebElementEntity>
